<!-- Lexoforms subscription details (compliance page only) -->
<section class="section" id="lexoforms-details">
  <div class="container">
    <div class="section-header">
      <h2 data-lang-en="Lexoforms: GDPR compliance subscription" data-lang-da="Lexoforms: GDPR compliance på abonnement">Lexoforms: GDPR compliance på abonnement</h2>
      <p data-lang-en="We help startups and SMEs get GDPR under control with a subscription program." data-lang-da="Sixtus og Lexoforms ønsker at hjælpe både startups og etablerede SMVs med at få styr på GDPR. Vi ved at GDPR ikke altid står øverst på listen, når man har travlt med at drive og vækste sin virksomhed.">Sixtus og Lexoforms ønsker at hjælpe både startups og etablerede SMVs med at få styr på GDPR. Vi ved at GDPR ikke altid står øverst på listen, når man har travlt med at drive og vækste sin virksomhed.</p>
    </div>
    <p data-lang-en="We make compliance simple. With a subscription, we handle the heavy lifting and work closely with you to analyse your business." data-lang-da="For at gøre det så nemt, som muligt, har vi lavet en abonnementsordning, hvor vi tager os af det tunge arbejde, og i samarbejde gennemanalyserer vi jeres virksomhed.">For at gøre det så nemt, som muligt, har vi lavet en abonnementsordning, hvor vi tager os af det tunge arbejde, og i samarbejde gennemanalyserer vi jeres virksomhed.</p>
    <p data-lang-en="We map IT systems and processes, review processor agreements, run risk analyses, and keep your GDPR foundation solid." data-lang-da="Dermed kan vi kortlægge alt lige fra IT-systemer til processer, tjekke databehandleraftaler, lave risikoanalyser og meget mere.">Dermed kan vi kortlægge alt lige fra IT-systemer til processer, tjekke databehandleraftaler, lave risikoanalyser og meget mere.</p>

    <p data-lang-en="With a GDPR subscription from Sixtus and Lexoforms, you always comply with current practice. The subscription always includes the base package:" data-lang-da="Med et GDPR-abonnement fra Sixtus og Lexoforms, får I en løsning der sikrer, at I overholder gældende praksis. Abonnementet er altid inkl. basispakken:">Med et GDPR-abonnement fra Sixtus og Lexoforms, får I en løsning der sikrer, at I overholder gældende praksis. Abonnementet er altid inkl. basispakken:</p>
    <ul class="icon-list">
      <li data-lang-en="A personal advisor who follows your company." data-lang-da="En personlig rådgiver, som følger jeres virksomhed og sikrer et stabilt samarbejde"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> En personlig rådgiver, som følger jeres virksomhed og sikrer et stabilt samarbejde</li>
      <li data-lang-en="Sixtus participates in the first Data Protection Authority meeting." data-lang-da="Deltagelse fra Sixtus i første møde ved tilsyn fra Datatilsynet"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Deltagelse fra Sixtus i første møde ved tilsyn fra Datatilsynet</li>
      <li data-lang-en="Website review." data-lang-da="Eftersyn af hjemmeside"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Eftersyn af hjemmeside</li>
      <li data-lang-en="Annual Lexoforms customer network meeting." data-lang-da="Årligt netværksmøde for vores Lexoforms kunder"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Årligt netværksmøde for vores Lexoforms kunder</li>
      <li data-lang-en="Preferred pricing on Sixtus Scanner." data-lang-da="Fordelagtige priser på Sixtus Scanner"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Fordelagtige priser på Sixtus Scanner</li>
    </ul>

    <p data-lang-en="In the first year, you also get:" data-lang-da="Det første år får I desuden følgende ydelser:">Det første år får I desuden følgende ydelser:</p>
    <p data-lang-en="First year price: 20,000 DKK excl. VAT + Lexoforms license 4,200 DKK excl. VAT" data-lang-da="Pris første år: 20.000 DKK ex. moms + Lexoforms licens: 4.200 DKK ex. moms">Pris første år: 20.000 DKK ex. moms + Lexoforms licens: 4.200 DKK ex. moms</p>
    <ul class="icon-list">
      <li data-lang-en="1-2 kick-off meetings." data-lang-da="1-2 opstartsmøder"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> 1-2 opstartsmøder</li>
      <li data-lang-en="Review of systems and processing activities." data-lang-da="Gennemgang jeres systemer og behandlingsaktiviteter"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Gennemgang jeres systemer og behandlingsaktiviteter</li>
      <li data-lang-en="Collect and review mandatory processor supervision." data-lang-da="Indsamling og gennemgang af obligatoriske tilsyn af databehandlere"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Indsamling og gennemgang af obligatoriske tilsyn af databehandlere</li>
      <li data-lang-en="Review of processor agreements." data-lang-da="Gennemgang af databehandleraftaler"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Gennemgang af databehandleraftaler</li>
      <li data-lang-en="Update and activate GDPR operations in Lexoforms." data-lang-da="Opdatering og igangsættelse af GDPR-drift i Lexoforms"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Opdatering og igangsættelse af GDPR-drift i Lexoforms</li>
      <li data-lang-en="3 hours of advisory for incidents or requests." data-lang-da="3 timers rådgivning, fx ved data brud, indsigtsanmodninger eller anden GDPR-konsultation"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> 3 timers rådgivning, fx ved data brud, indsigtsanmodninger eller anden GDPR-konsultation</li>
    </ul>

    <p data-lang-en="In subsequent years, the base package still applies and you get:" data-lang-da="Efterfølgende år er “basispakken” stadig gældende, og ydelserne vil derudover se således ud:">Efterfølgende år er “basispakken” stadig gældende, og ydelserne vil derudover se således ud:</p>
    <p data-lang-en="Annual price: 12,500 DKK excl. VAT, includes:" data-lang-da="Pris pr. år herefter: 12.500 DKK ex. moms. og inkluderer:">Pris pr. år herefter: 12.500 DKK ex. moms. og inkluderer:</p>
    <ul class="icon-list">
      <li data-lang-en="Lexoforms license." data-lang-da="Lexoforms licens"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Lexoforms licens</li>
      <li data-lang-en="Annual recap meeting." data-lang-da="Årligt opsamlingsmøde"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Årligt opsamlingsmøde</li>
      <li data-lang-en="2 hours of advisory for incidents or requests." data-lang-da="2 timers rådgivning, fx ved data brud, indsigtsanmodninger eller anden GDPR-konsultation"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> 2 timers rådgivning, fx ved data brud, indsigtsanmodninger eller anden GDPR-konsultation</li>
      <li data-lang-en="Review and update systems and processing activities." data-lang-da="Gennemgang og opdatering af systemer og behandlingsaktiviteter"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Gennemgang og opdatering af systemer og behandlingsaktiviteter</li>
      <li data-lang-en="Collect and review mandatory processor supervision." data-lang-da="Indsamling og gennemgang af obligatoriske tilsyn af databehandlere"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Indsamling og gennemgang af obligatoriske tilsyn af databehandlere</li>
      <li data-lang-en="Review of processor agreements." data-lang-da="Gennemgang af databehandleraftaler"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Gennemgang af databehandleraftaler</li>
    </ul>
  </div>
</section>

<!-- Whistleblower software details -->
<section class="section" id="whistleblower-details">
  <div class="container">
    <div class="section-header">
      <h2 data-lang-en="Whistleblower Software" data-lang-da="Whistleblower Software">Whistleblower Software</h2>
      <p data-lang-en="Minimize your risk and create transparency." data-lang-da="Minimer din risiko og skab gennemsigtighed">Minimer din risiko og skab gennemsigtighed</p>
    </div>
    <p data-lang-en="Sixtus delivers, in collaboration with our partner Whistleblower Software ApS, a strong whistleblower program for companies that want transparency and high confidentiality for whistleblowers." data-lang-da="Sixtus tilbyder, i samarbejde med vores partner Whistleblower Software Aps, et stærkt whistleblowerprogram, for virksomheder, der ønsker at sikre gennemsigtighed og høj fortrolighed for whistlebloweren.">Sixtus tilbyder, i samarbejde med vores partner Whistleblower Software Aps, et stærkt whistleblowerprogram, for virksomheder, der ønsker at sikre gennemsigtighed og høj fortrolighed for whistlebloweren.</p>
    <p data-lang-en="Whistleblower Software, now ISAE 3000 certified, has developed software that defines a new generation of whistleblower services. The system is easy to set up and manage and allows anonymous, confidential, or both types of reporting. It also ensures cases are always forwarded to the right parties in the company." data-lang-da="Whistleblower Software, der netop er blevet ISAE 3000-certificeret, har udviklet et nyt software, der er med til at definere en ny generation af whistleblowertjenester. Systemet er brugervenligt, både i opsætning og administration og giver mulighed for at kunne rapportere anonymt, fortroligt eller begge dele. Samtidig sikres det at sagerne altid bliver videregivet til de korrekte parter i virksomheden.">Whistleblower Software, der netop er blevet ISAE 3000-certificeret, har udviklet et nyt software, der er med til at definere en ny generation af whistleblowertjenester. Systemet er brugervenligt, både i opsætning og administration og giver mulighed for at kunne rapportere anonymt, fortroligt eller begge dele. Samtidig sikres det at sagerne altid bliver videregivet til de korrekte parter i virksomheden.</p>
    <p data-lang-en="Want to hear more about Whistleblower Software? Contact us at +45 30 65 43 35 or info@sixtus-compliance.dk." data-lang-da="Vil du høre mere om Whistleblower Software? Kontakt os på +45 30 65 43 35 eller info@sixtus-compliance.dk">Vil du høre mere om Whistleblower Software? Kontakt os på +45 30 65 43 35 eller info@sixtus-compliance.dk</p>

    <h3 data-lang-en="You can still make it!" data-lang-da="Du kan stadig nå det!">Du kan stadig nå det!</h3>
    <p data-lang-en="Today most large listed companies have a whistleblower program. But as of 17 December 2021 all private companies with 250+ employees are required to have a whistleblower program. For private sector companies with 50-249 employees, the deadline to establish whistleblower arrangements is 17 December 2023." data-lang-da="I dag har de fleste store, børsnoterede virksomheder et whistleblowerprogram. Men pr. 17. december 2021 har alle private virksomheder med 250+ ansatte, været forpligtet til at have et whistleblowerprogram. For virksomheder i den private sektor med mellem 50-249 ansatte, udløber fristen til at etablere whistleblowerordninger dog først 17. december 2023.">I dag har de fleste store, børsnoterede virksomheder et whistleblowerprogram. Men pr. 17. december 2021 har alle private virksomheder med 250+ ansatte, været forpligtet til at have et whistleblowerprogram. For virksomheder i den private sektor med mellem 50-249 ansatte, udløber fristen til at etablere whistleblowerordninger dog først 17. december 2023.</p>

    <h3 data-lang-en="Whistleblower scheme with Sixtus" data-lang-da="Whistleblowerordning med Sixtus">Whistleblowerordning med Sixtus</h3>
    <p data-lang-en="The key requirement is protecting whistleblowers from consequences linked to good-faith reports. Emails with internal users are not enough; companies must ensure the whistleblower’s identity is 100% confidential." data-lang-da="Fælles er for alle er, at det skal kunne sikres, at whistlebloweren bliver beskyttet mod de potentielle konsekvenser, som er forbundet med en indberetning afgivet i god tro. Dermed er e-mails med interne brugere heller ikke nok; virksomheden skal sikre, at whistleblowerens identitet kan holdes 100% fortrolig.">Fælles er for alle er, at det skal kunne sikres, at whistlebloweren bliver beskyttet mod de potentielle konsekvenser, som er forbundet med en indberetning afgivet i god tro. Dermed er e-mails med interne brugere heller ikke nok; virksomheden skal sikre, at whistleblowerens identitet kan holdes 100% fortrolig.</p>
    <p data-lang-en="With Sixtus by your side, you get help with implementation and support throughout the process. The implementation package includes the following services:" data-lang-da="Med Sixtus på sidelinjen, får du hjælp til implementering og support i hele processen. Implementeringspakken inkluderer følgende services:">Med Sixtus på sidelinjen, får du hjælp til implementering og support i hele processen. Implementeringspakken inkluderer følgende services:</p>
    <ul class="icon-list icon-list--columns">
      <li data-lang-en="Internal training" data-lang-da="Intern undervisning"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Intern undervisning</li>
      <li data-lang-en="Implementation of whistleblower policy" data-lang-da="Implementering af whistleblowerpolitik"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Implementering af whistleblowerpolitik</li>
      <li data-lang-en="Implementation of internal processes" data-lang-da="Implementering af interne processer"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Implementering af interne processer</li>
      <li data-lang-en="Processes for handling reports" data-lang-da="Processer for håndteringen af anmeldelser"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Processer for håndteringen af anmeldelser</li>
      <li data-lang-en="Help setting up an internal/external whistleblower board" data-lang-da="Hjælp til oprettelse af et internt/eksternt whistleblowerboard"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Hjælp til oprettelse af et internt/eksternt whistleblowerboard</li>
      <li data-lang-en="Monitoring, validation, and handling of incoming cases" data-lang-da="Overvågning, validering og håndtering af indkomne sager"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Overvågning, validering og håndtering af indkomne sager</li>
      <li data-lang-en="Access to legal assistance in complex cases" data-lang-da="Adgang til juridisk bistand ved komplicerede sager"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Adgang til juridisk bistand ved komplicerede sager</li>
      <li data-lang-en="Reporting and report writing" data-lang-da="Rapportering og rapportskrivning"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Rapportering og rapportskrivning</li>
    </ul>
  </div>
</section>
