<!-- DPO service deep-dive section -->
<?php $section_id = isset($args['section_id']) ? $args['section_id'] : 'compliance-details'; ?>
<section class="section" id="<?php echo esc_attr($section_id); ?>">
  <div class="container">
    <div class="section-header">
      <h2 data-lang-en="DPO as a Service" data-lang-da="DPO as a Service">DPO as a Service</h2>
      <p data-lang-en="We keep your company GDPR compliant with structured advisory, documentation, and continuous oversight." data-lang-da="Vi holder din virksomhed GDPR compliant med struktureret rådgivning, dokumentation og løbende oversight.">Vi holder din virksomhed GDPR compliant</p>
    </div>
    <p data-lang-en="As your external Data Protection Officer, we translate GDPR obligations into daily practice and support your team with documentation, notifications, and regulator contact." data-lang-da="Som ekstern databeskyttelsesrådgiver (DPO) gør vi det nemmere for din virksomhed at leve op til de gældende GDPR-krav og omsætte reglerne for databeskyttelse til praksis.">Som ekstern databeskyttelsesrådgiver (DPO) gør vi det nemmere for din virksomhed at leve op til de gældende GDPR krav og omsætte reglerne for databeskyttelse til praksis.</p>
    <p data-lang-en="We ensure documentation, progress, and reporting so you remain compliant and have an independent advisor and contact point for the Data Protection Authority." data-lang-da="Vi sørger for dokumentation, fremdrift og underretninger, så I løbende overholder persondataforordningen. Vi fungerer også som uvildig rådgiver og kontaktperson til Datatilsynet.">Vi sørger for dokumentation, fremdrift og underretninger, så I løbende overholder persondataforordningen. Vi fungerer også som uvildig rådgiver og kontaktperson til Datatilsynet.</p>
    <p data-lang-en="Hear how we can help your business. Contact us on +45 30 65 43 35 or write to us." data-lang-da="Hør hvordan vi kan hjælpe din virksomhed. Kontakt os på +45 30 65 43 35 eller skriv til os:">Hør hvordan vi kan hjælpe din virksomhed. Kontakt os på +45 30 65 43 35 eller skriv til os:</p>
    <div class="button-group button-group--spaced">
      <a class="btn btn-primary" href="<?php echo esc_url(home_url('/contact')); ?>" data-lang-en="Contact us" data-lang-da="Kontakt os">Kontakt os</a>
    </div>

    <div class="section section-spaced">
      <div class="section-header">
        <h2 data-lang-en="Be ready when GDPR requirements change" data-lang-da="Vær klar når GDPR-kravene opdateres">Vær klar når GDPR-kravene opdateres</h2>
      </div>
      <p data-lang-en="Persondataforordningen er et levende dokument, hvis overholdelse præciseres af de sager, som Datatilsynet træffer afgørelse i. Det er derfor nødvendigt at følge en GDPR-køreplan, der viser at man som virksomhed er opdateret ift. beskyttelse af persondata." data-lang-da="Persondataforordningen er et levende dokument, hvis overholdelse præciseres af de sager, som Datatilsynet træffer afgørelse i. Det er derfor nødvendigt at følge en GDPR-køreplan, der viser at man som virksomhed er opdateret ift. beskyttelse af persondata.">Persondataforordningen er et levende dokument, hvis overholdelse præciseres af de sager, som Datatilsynet træffer afgørelse i. Det er derfor nødvendigt at følge en GDPR-køreplan, der viser at man som virksomhed er opdateret ift. beskyttelse af persondata.</p>
      <p data-lang-en="Vi tilbyder DPO aaS til virksomheder, som ønsker en ekstern databeskyttelsesrådgiver. På den måde har I kun udgifter til de faste opgaver, ligesom det er let at skalere op efter behov – fx hvis der sker et sikkerhedsbrud. En DPO rådgiver arbejder tæt sammen med virksomhedens dataansvarlige, men skal have mulighed for at give uvildig rådgivning." data-lang-da="Vi tilbyder DPO aaS til virksomheder, som ønsker en ekstern databeskyttelsesrådgiver. På den måde har I kun udgifter til de faste opgaver, ligesom det er let at skalere op efter behov – fx hvis der sker et sikkerhedsbrud. En DPO rådgiver arbejder tæt sammen med virksomhedens dataansvarlige, men skal have mulighed for at give uvildig rådgivning.">Vi tilbyder DPO aaS til virksomheder, som ønsker en ekstern databeskyttelsesrådgiver. På den måde har I kun udgifter til de faste opgaver, ligesom det er let at skalere op efter behov – fx hvis der sker et sikkerhedsbrud. En DPO rådgiver arbejder tæt sammen med virksomhedens dataansvarlige, men skal have mulighed for at give uvildig rådgivning.</p>
    </div>

  <div class="card card-spaced">
      <h3 data-lang-en="With DPO service from Sixtus you get:" data-lang-da="Med DPO service fra Sixtus får din virksomhed:">Med DPO service fra Sixtus får din virksomhed:</h3>
      <ul class="icon-list">
        <li data-lang-en="Registration governance with the Data Protection Authority." data-lang-da="Styr på alle registreringer hos Datatilsynet"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Styr på alle registreringer hos Datatilsynet</li>
        <li data-lang-en="Correct handling of data processor agreements." data-lang-da="Korrekt håndtering af databehandleraftaler"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Korrekt håndtering af databehandleraftaler</li>
        <li data-lang-en="Implementation of required procedures and DPIAs." data-lang-da="Implementering af alle nødvendige procedurer og DPIAs"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Implementering af alle nødvendige procedurer</li>
        <li data-lang-en="Support for access requests." data-lang-da="Assistance ifbm. indsigtsanmodninger"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Assistance ifbm. indsigtsanmodninger</li>
        <li data-lang-en="DPIA impact and risk analyses." data-lang-da="Konsekvens- og risikoanalyser (DPIAs)"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Konsekvens- og risikoanalyser (DPIAs)</li>
        <li data-lang-en="IT procedure guidance." data-lang-da="Rådgivning om IT-procedurer ift. GDPR compliance"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Rådgivning om IT-procedurer ift. GDPR compliance</li>
        <li data-lang-en="Incident response support." data-lang-da="Akut support i tilfælde af databrud"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Akut support i tilfælde af databrud</li>
        <li data-lang-en="Annual review with documentation updates." data-lang-da="Årligt eftersyn med opdatering af al dokumentation"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Årligt eftersyn med opdatering af al dokumentation</li>
        <li data-lang-en="Ongoing review of internal data handling." data-lang-da="Løbende revision af den interne datahåndtering og dokumentation"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Løbende revision af den interne datahåndtering og dokumentation</li>
        <li data-lang-en="Support in external audits." data-lang-da="Support og rådgivning i tilfælde af ekstern audit"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Support og rådgivning i tilfælde af ekstern audit</li>
        <li data-lang-en="Internal training in correct handling of personal data." data-lang-da="Intern uddannelse i korrekt håndtering af persondata"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Intern uddannelse i korrekt håndtering af persondata</li>
        <li data-lang-en="Access to Sixtus Scanner." data-lang-da="Adgang til Sixtus Scanner"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Adgang til Sixtus Scanner</li>
      </ul>
    </div>

  <div class="section section-spaced">
      <div class="section-header">
        <h2 data-lang-en="Which companies need a DPO?" data-lang-da="Hvilke virksomheder skal have en DPO?">Hvilke virksomheder skal have en DPO?</h2>
      </div>
      <p data-lang-en="Ifølge persondataforordningen er det kun virksomheder, hvis kerneaktivitet er behandling af personoplysninger, virksomheder der i stort omfang behandler personoplysninger og følsomme oplysninger, samt virksomheder, som systematisk har personer registreret." data-lang-da="Ifølge persondataforordningen er det kun virksomheder, hvis kerneaktivitet er behandling af personoplysninger, virksomheder der i stort omfang behandler personoplysninger og følsomme oplysninger, samt virksomheder, som systematisk har personer registreret.">Ifølge persondataforordningen er det kun virksomheder, hvis kerneaktivitet er behandling af personoplysninger, virksomheder der i stort omfang behandler personoplysninger og følsomme oplysninger, samt virksomheder, som systematisk har personer registreret.</p>
      <p data-lang-en="If you are in doubt, contact us for independent advice." data-lang-da="Hvis du er i tvivl om din virksomhed skal have en DPO, så er du velkommen til at kontakte os for uvildig rådgivning.">Hvis du er i tvivl om din virksomhed skal have en DPO, så er du velkommen til at kontakte os for uvildig rådgivning.</p>
    </div>

  <div class="section section-spaced">
      <div class="section-header">
        <h2 data-lang-en="Audit readiness & ISAE reporting" data-lang-da="Erklæringsklargøring">Erklæringsklargøring</h2>
        <p data-lang-en="We deliver ISAE 3000/3402 type 1 and type 2 statements for larger companies that require this form of assurance." data-lang-da="Vi tilbyder en ISAE 3000/3402 type 1 og type 2 til større virksomheder, der har krav om denne form for revision i deres databehandleraftaler.">Vi tilbyder en ISAE 3000/3402 type 1 og type 2 til større virksomheder, der har krav om denne form for revision i deres databehandleraftaler.</p>
      </div>
      <p data-lang-en="Sixtus can assist with control testing, collecting and structuring documentation, and evidence for these tests. We also prepare audit texts so you can deliver a complete package to the auditor that forms the basis for the report." data-lang-da="Sixtus kan assistere med klargøring til kontroltests, hjælpe med indsamling og strukturering af dokumentation og bevisførelse ift. disse tests. Derudover kan vi assistere med klargøring af revisionstekster, således at I kan levere en samlet pakke til revisoren, som skal danne grundlag for rapporten.">Sixtus kan assistere med klargøring til kontroltests, hjælpe med indsamling og strukturering af dokumentation og bevisførelse ift. disse tests. Derudover kan vi assistere med klargøring af revisionstekster, således at I kan levere en samlet pakke til revisoren, som skal danne grundlag for rapporten.</p>
      <p data-lang-en="Unlike an audit firm, we can also advise on errors or gaps and how to mitigate them going forward, streamlining processes, procedures, and policies." data-lang-da="Samtidig vil vi, i modsætning til et revisionshus, kunne levere rådgivning ift. fejl eller mangler og hvordan disse mitigeres fremadrettet. Dermed kan vi sørge for en strømlining af både processer, procedurer og politikker på området.">Samtidig vil vi, i modsætning til et revisionshus, kunne levere rådgivning ift. fejl eller mangler og hvordan disse mitigeres fremadrettet. Dermed kan vi sørge for en strømlining af både processer, procedurer og politikker på området.</p>
      <p data-lang-en="We also offer an IT security inspection for SMEs without formal assurance requirements, so you can show customers that you protect their data." data-lang-da="Udover ovenstående kan vi også tilbyde en IT-sikkerheds inspektion. Denne løsning er ideel for SMV’er, der ikke har krav fra samarbejdspartnere ift. hvilken type årlig erklæring de skal levere. Med inspektionen vil I også være i stand til at vise jeres kunder, at I passer godt på deres data.">Udover ovenstående kan vi også tilbyde en IT-sikkerheds inspektion. Denne løsning er ideel for SMV’er, der ikke har krav fra samarbejdspartnere ift. hvilken type årlig erklæring de skal levere. Med inspektionen vil I også være i stand til at vise jeres kunder, at I passer godt på deres data.</p>
    </div>

  <div class="section section-spaced">
      <div class="section-header">
        <h2 data-lang-en="GDPR & privacy projects" data-lang-da="GDPR og privacy projekter">GDPR og privacy projekter</h2>
        <p data-lang-en="Personal data moves faster than ever and everyone has the right to access their data or be forgotten. That limits how businesses collect and store data." data-lang-da="Persondata flyder hurtigere end nogensinde før og alle har ret til indsigt i egne data og til at blive glemt. Netop derfor begrænses virksomheders ret til at indhente og opbevare persondata.">Persondata flyder hurtigere end nogensinde før og alle har ret til indsigt i egne data og til at blive glemt. Netop derfor begrænses virksomheders ret til at indhente og opbevare persondata.</p>
      </div>
      <p data-lang-en="This often means a new GDPR practice where workflows, services, and products must change." data-lang-da="Dette indebærer ofte etableringen af en ny GDPR-praksis, hvor både arbejdsgange, men også ydelser og produkter skal ændres.">Dette indebærer ofte etableringen af en ny GDPR-praksis, hvor både arbejdsgange, men også ydelser og produkter skal ændres.</p>
      <p data-lang-en="Want to hear more about our GDPR services? Contact Bo on +45 30 65 43 35 or write to us:" data-lang-da="Vil du høre mere om vores GDPR services? Så kontakt Bo på +45 30 65 43 35 eller skriv til os:">Vil du høre mere om vores GDPR services? Så kontakt Bo på +45 30 65 43 35 eller skriv til os:</p>
      <div class="button-group button-group--spaced">
        <a class="btn btn-primary" href="<?php echo esc_url(home_url('/contact')); ?>" data-lang-en="Contact us" data-lang-da="Kontakt os">Kontakt os</a>
      </div>

      <div class="section section-spaced">
        <div class="section-header">
          <h2 data-lang-en="Integrate GDPR into all services and products" data-lang-da="Integrer GDPR i alle ydelser og produkter">Integrer GDPR i alle ydelser og produkter</h2>
        </div>
        <p data-lang-en="Sixtus trains your employees in GDPR compliance and tailors the program to your company. We always start with a workshop, identify the tools you need, and integrate or reuse existing systems. You also get:" data-lang-da="Sixtus kan hjælpe med at uddanne dine medarbejdere i GDPR compliance og vi skræddersyer forløbet til jeres virksomhed. Et samarbejde indledes altid med en workshop, vi ser på hvilke nye redskaber, din virksomhed har brug for og hvilke eksisterende systemer, der kan integreres eller genbruges. Derudover får I:">Sixtus kan hjælpe med at uddanne dine medarbejdere i GDPR compliance og vi skræddersyer forløbet til jeres virksomhed. Et samarbejde indledes altid med en workshop, vi ser på hvilke nye redskaber, din virksomhed har brug for og hvilke eksisterende systemer, der kan integreres eller genbruges. Derudover får I:</p>
        <ul class="icon-list">
          <li data-lang-en="Review and analysis of all business processes for data collection and storage." data-lang-da="Gennemgået og analyseret alle forretningsprocesser ifm. indsamling og opbevaring af data"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Gennemgået og analyseret alle forretningsprocesser ifm. indsamling og opbevaring af data</li>
          <li data-lang-en="Assessment of IT security needs and GDPR steps." data-lang-da="Afdækket behov for IT-sikkerhed og afdækker de nødvendige skridt mod GDPR compliance"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Afdækket behov for IT-sikkerhed og afdækker de nødvendige skridt mod GDPR compliance</li>
          <li data-lang-en="Assessment of the need for a DPO." data-lang-da="Afdækket nødvendighed for en databeskyttelsesrådgiver (DPO)"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Afdækket nødvendighed for en databeskyttelsesrådgiver (DPO)</li>
          <li data-lang-en="Recommendations, checklists, and required standards." data-lang-da="Anbefalinger, solide tjeklister og nødvendige standarder"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Anbefalinger, solide tjeklister og nødvendige standarder</li>
          <li data-lang-en="3-5 implementation meetings based on scope." data-lang-da="3-5 implementeringsmøder afhængig af opgaven og virksomhedens størrelse."><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> 3-5 implementeringsmøder afhængig af opgaven og virksomhedens størrelse.</li>
        </ul>
      </div>

      <div class="section section-spaced">
        <div class="section-header">
          <h3 data-lang-en="We make sure your company:" data-lang-da="Vi sørger for at jeres virksomhed:">Vi sørger for at jeres virksomhed:</h3>
        </div>
        <ul class="icon-list">
          <li data-lang-en="Builds a GDPR mindset across leadership and staff." data-lang-da="Opbygger et GDPR-mindset hos ledelse og medarbejdere"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Opbygger et GDPR-mindset hos ledelse og medarbejdere</li>
          <li data-lang-en="Can describe procedures in case of data breaches." data-lang-da="Kan beskrive procedurer i tilfælde af databrud"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Kan beskrive procedurer i tilfælde af databrud</li>
          <li data-lang-en="Has control of data subject rights and consent." data-lang-da="Har styr på alle registreredes rettigheder, herunder de nødvendige samtykkeeklæringer"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Har styr på alle registreredes rettigheder, herunder de nødvendige samtykkeeklæringer</li>
          <li data-lang-en="Has IT procedures for security, privacy settings, and recovery." data-lang-da="Har IT-procedurer for sikkerhed, privatslivsindstillinger og genoprettelse efter nedbrud"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Har IT-procedurer for sikkerhed, privatslivsindstillinger og genoprettelse efter nedbrud</li>
          <li data-lang-en="Implements the necessary management tools." data-lang-da="Implementerer de nødvendige ledelsesværktøjer"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Implementerer de nødvendige ledelsesværktøjer</li>
          <li data-lang-en="Has support for GDPR audits." data-lang-da="Har support til GDPR audit."><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Har support til GDPR audit.</li>
        </ul>
      </div>
    </div>

  <div class="section section-spaced">
      <div class="section-header">
        <h2 data-lang-en="Internal compliance & audit" data-lang-da="Intern compliance og revision">Intern compliance og revision</h2>
        <p data-lang-en="On-demand compliance support for SMEs with 1–2 days per week coverage." data-lang-da="Servicen er målrettet SMV’er, der har behov for en compliance afdeling on demand.">Servicen er målrettet SMV’er, der grundet fx branche– eller områdespecifikke eksterne krav har behov for en compliance afdeling “on demand”.</p>
      </div>
      <p data-lang-en="We cover IT security, GDPR, vendor risk, and whistleblowing with dedicated advisors." data-lang-da="Vi kan fx håndtere compliance inden for områder som IT-sikkerhed, GDPR, Vendor Risk Management, whistleblowing eller lign. Fokus vil være på områder, der ikke nødvendigvis kræver en fuldtidsressource, men alligevel har brug for opmærksomhed 1-2 dage om ugen.">Vi kan fx håndtere compliance inden for områder som IT-sikkerhed, GDPR, Vendor Risk Management, whistleblowing eller lign. Fokus vil være på områder, der ikke nødvendigvis kræver en fuldtidsressource, men alligevel har brug for opmærksomhed 1-2 dage om ugen.</p>
      <p data-lang-en="We also support internal advisory for development projects and assist with privacy by design and privacy by default. A dedicated Sixtus specialist can focus on the areas you need, with pricing based on scope and monthly days." data-lang-da="Sixtus er også i stand til at varetage den interne rådgivning ift. udviklingsprojekter og assistere med bl.a. privacy by design og privacy by default. I får en af vores dygtige medarbejdere til stillet rådighed, således at hun eller han kan håndtere netop de områder I ønsker. Prisen varierer afhængig af løsningens størrelse, samt det antal dage måneden medarbejderen skal være til rådighed.">Sixtus er også i stand til at varetage den interne rådgivning ift. udviklingsprojekter og assistere med bl.a. privacy by design og privacy by default. I får en af vores dygtige medarbejdere til stillet rådighed, således at hun eller han kan håndtere netop de områder I ønsker. Prisen varierer afhængig af løsningens størrelse, samt det antal dage måneden medarbejderen skal være til rådighed.</p>
      <p data-lang-en="Your compliance and audit specialist will typically cost 12–15,000 DKK per day depending on scope. Contact us for a tailored offer." data-lang-da="Jeres nye compliance– og revisionsmedarbejder vil, afhængig af aftalens omfang koste mellem 12-15.000 DKK pr. dag, men I er velkomne til at kontakte os, så vi kan tage snak om jeres konkrete udfordringer og lave et tilbud på en løsningen til jer.">Jeres nye compliance– og revisionsmedarbejder vil, afhængig af aftalens omfang koste mellem 12-15.000 DKK pr. dag, men I er velkomne til at kontakte os, så vi kan tage snak om jeres konkrete udfordringer og lave et tilbud på en løsningen til jer.</p>
    </div>

<?php if (!isset($args['include_extras']) || $args['include_extras']) : ?>
  <div class="section section-spaced">
      <div class="section-header">
        <h2 data-lang-en="Lexoforms: GDPR compliance subscription" data-lang-da="Lexoforms: GDPR compliance på abonnement">Lexoforms: GDPR compliance på abonnement</h2>
        <p data-lang-en="We help startups and SMEs get GDPR under control with a subscription program." data-lang-da="Sixtus og Lexoforms ønsker at hjælpe både startups og etablerede SMVs med at få styr på GDPR. Vi ved at GDPR ikke altid står øverst på listen, når man har travlt med at drive og vækste sin virksomhed.">Sixtus og Lexoforms ønsker at hjælpe både startups og etablerede SMVs med at få styr på GDPR. Vi ved at GDPR ikke altid står øverst på listen, når man har travlt med at drive og vækste sin virksomhed.</p>
      </div>
  <p data-lang-en="We make compliance simple. With a subscription, we handle the heavy lifting and work closely with you to analyse your business." data-lang-da="For at gøre det så nemt, som muligt, har vi lavet en abonnementsordning, hvor vi tager os af det tunge arbejde, og i samarbejde gennemanalyserer vi jeres virksomhed.">For at gøre det så nemt, som muligt, har vi lavet en abonnementsordning, hvor vi tager os af det tunge arbejde, og i samarbejde gennemanalyserer vi jeres virksomhed.</p>
  <p data-lang-en="We map IT systems and processes, review processor agreements, run risk analyses, and keep your GDPR foundation solid." data-lang-da="Dermed kan vi kortlægge alt lige fra IT-systemer til processer, tjekke databehandleraftaler, lave risikoanalyser og meget mere.">Dermed kan vi kortlægge alt lige fra IT-systemer til processer, tjekke databehandleraftaler, lave risikoanalyser og meget mere.</p>

  <p data-lang-en="With a GDPR subscription from Sixtus and Lexoforms, you always comply with current practice. The subscription always includes the base package:" data-lang-da="Med et GDPR-abonnement fra Sixtus og Lexoforms, får I en løsning der sikrer, at I overholder gældende praksis. Abonnementet er altid inkl. basispakken:">Med et GDPR-abonnement fra Sixtus og Lexoforms, får I en løsning der sikrer, at I overholder gældende praksis. Abonnementet er altid inkl. basispakken:</p>
      <ul class="icon-list">
        <li data-lang-en="A personal advisor who follows your company." data-lang-da="En personlig rådgiver, som følger jeres virksomhed og sikrer et stabilt samarbejde"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> En personlig rådgiver, som følger jeres virksomhed og sikrer et stabilt samarbejde</li>
        <li data-lang-en="Sixtus participates in the first Data Protection Authority meeting." data-lang-da="Deltagelse fra Sixtus i første møde ved tilsyn fra Datatilsynet"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Deltagelse fra Sixtus i første møde ved tilsyn fra Datatilsynet</li>
        <li data-lang-en="Website review." data-lang-da="Eftersyn af hjemmeside"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Eftersyn af hjemmeside</li>
        <li data-lang-en="Annual Lexoforms customer network meeting." data-lang-da="Årligt netværksmøde for vores Lexoforms kunder"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Årligt netværksmøde for vores Lexoforms kunder</li>
        <li data-lang-en="Preferred pricing on Sixtus Scanner." data-lang-da="Fordelagtige priser på Sixtus Scanner"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Fordelagtige priser på Sixtus Scanner</li>
      </ul>

  <p data-lang-en="In the first year, you also get:" data-lang-da="Det første år får I desuden følgende ydelser:">Det første år får I desuden følgende ydelser:</p>
  <p data-lang-en="First year price: 20,000 DKK excl. VAT + Lexoforms license 4,200 DKK excl. VAT" data-lang-da="Pris første år: 20.000 DKK ex. moms + Lexoforms licens: 4.200 DKK ex. moms">Pris første år: 20.000 DKK ex. moms + Lexoforms licens: 4.200 DKK ex. moms</p>
      <ul class="icon-list">
        <li data-lang-en="1-2 kick-off meetings." data-lang-da="1-2 opstartsmøder"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> 1-2 opstartsmøder</li>
        <li data-lang-en="Review of systems and processing activities." data-lang-da="Gennemgang jeres systemer og behandlingsaktiviteter"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Gennemgang jeres systemer og behandlingsaktiviteter</li>
        <li data-lang-en="Collect and review mandatory processor supervision." data-lang-da="Indsamling og gennemgang af obligatoriske tilsyn af databehandlere"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Indsamling og gennemgang af obligatoriske tilsyn af databehandlere</li>
        <li data-lang-en="Review of processor agreements." data-lang-da="Gennemgang af databehandleraftaler"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Gennemgang af databehandleraftaler</li>
        <li data-lang-en="Update and activate GDPR operations in Lexoforms." data-lang-da="Opdatering og igangsættelse af GDPR-drift i Lexoforms"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Opdatering og igangsættelse af GDPR-drift i Lexoforms</li>
        <li data-lang-en="3 hours of advisory for incidents or requests." data-lang-da="3 timers rådgivning, fx ved data brud, indsigtsanmodninger eller anden GDPR-konsultation"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> 3 timers rådgivning, fx ved data brud, indsigtsanmodninger eller anden GDPR-konsultation</li>
      </ul>

  <p data-lang-en="In subsequent years, the base package still applies and you get:" data-lang-da="Efterfølgende år er “basispakken” stadig gældende, og ydelserne vil derudover se således ud:">Efterfølgende år er “basispakken” stadig gældende, og ydelserne vil derudover se således ud:</p>
      <p data-lang-en="Annual price: 12,500 DKK excl. VAT, includes:" data-lang-da="Pris pr. år herefter: 12.500 DKK ex. moms. og inkluderer:">Pris pr. år herefter: 12.500 DKK ex. moms. og inkluderer:</p>
      <ul class="icon-list">
        <li data-lang-en="Lexoforms license." data-lang-da="Lexoforms licens"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Lexoforms licens</li>
        <li data-lang-en="Annual recap meeting." data-lang-da="Årligt opsamlingsmøde"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Årligt opsamlingsmøde</li>
        <li data-lang-en="2 hours of advisory for incidents or requests." data-lang-da="2 timers rådgivning, fx ved data brud, indsigtsanmodninger eller anden GDPR-konsultation"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> 2 timers rådgivning, fx ved data brud, indsigtsanmodninger eller anden GDPR-konsultation</li>
        <li data-lang-en="Review and update systems and processing activities." data-lang-da="Gennemgang og opdatering af systemer og behandlingsaktiviteter"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Gennemgang og opdatering af systemer og behandlingsaktiviteter</li>
        <li data-lang-en="Collect and review mandatory processor supervision." data-lang-da="Indsamling og gennemgang af obligatoriske tilsyn af databehandlere"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Indsamling og gennemgang af obligatoriske tilsyn af databehandlere</li>
        <li data-lang-en="Review of processor agreements." data-lang-da="Gennemgang af databehandleraftaler"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Gennemgang af databehandleraftaler</li>
      </ul>
    </div>

  <div class="section section-spaced">
      <div class="section-header">
        <h2 data-lang-en="Whistleblower Software" data-lang-da="Whistleblower Software">Whistleblower Software</h2>
        <p data-lang-en="Minimize your risk and create transparency." data-lang-da="Minimer din risiko og skab gennemsigtighed">Minimer din risiko og skab gennemsigtighed</p>
      </div>
      <p data-lang-en="Sixtus delivers, in collaboration with our partner Whistleblower Software ApS, a strong whistleblower program for companies that want transparency and high confidentiality for whistleblowers." data-lang-da="Sixtus tilbyder, i samarbejde med vores partner Whistleblower Software Aps, et stærkt whistleblowerprogram, for virksomheder, der ønsker at sikre gennemsigtighed og høj fortrolighed for whistlebloweren.">Sixtus tilbyder, i samarbejde med vores partner Whistleblower Software Aps, et stærkt whistleblowerprogram, for virksomheder, der ønsker at sikre gennemsigtighed og høj fortrolighed for whistlebloweren.</p>
      <p data-lang-en="Whistleblower Software, now ISAE 3000 certified, has developed software that defines a new generation of whistleblower services. The system is easy to set up and manage and allows anonymous, confidential, or both types of reporting. It also ensures cases are always forwarded to the right parties in the company." data-lang-da="Whistleblower Software, der netop er blevet ISAE 3000-certificeret, har udviklet et nyt software, der er med til at definere en ny generation af whistleblowertjenester. Systemet er brugervenligt, både i opsætning og administration og giver mulighed for at kunne rapportere anonymt, fortroligt eller begge dele. Samtidig sikres det at sagerne altid bliver videregivet til de korrekte parter i virksomheden.">Whistleblower Software, der netop er blevet ISAE 3000-certificeret, har udviklet et nyt software, der er med til at definere en ny generation af whistleblowertjenester. Systemet er brugervenligt, både i opsætning og administration og giver mulighed for at kunne rapportere anonymt, fortroligt eller begge dele. Samtidig sikres det at sagerne altid bliver videregivet til de korrekte parter i virksomheden.</p>
      <p data-lang-en="Want to hear more about Whistleblower Software? Contact us at +45 30 65 43 35 or info@sixtus-compliance.dk." data-lang-da="Vil du høre mere om Whistleblower Software? Kontakt os på +45 30 65 43 35 eller info@sixtus-compliance.dk">Vil du høre mere om Whistleblower Software? Kontakt os på +45 30 65 43 35 eller info@sixtus-compliance.dk</p>

      <h3 data-lang-en="You can still make it!" data-lang-da="Du kan stadig nå det!">Du kan stadig nå det!</h3>
      <p data-lang-en="Today most large listed companies have a whistleblower program. But as of 17 December 2021 all private companies with 250+ employees are required to have a whistleblower program. For private sector companies with 50-249 employees, the deadline to establish whistleblower arrangements is 17 December 2023." data-lang-da="I dag har de fleste store, børsnoterede virksomheder et whistleblowerprogram. Men pr. 17. december 2021 har alle private virksomheder med 250+ ansatte, været forpligtet til at have et whistleblowerprogram. For virksomheder i den private sektor med mellem 50-249 ansatte, udløber fristen til at etablere whistleblowerordninger dog først 17. december 2023.">I dag har de fleste store, børsnoterede virksomheder et whistleblowerprogram. Men pr. 17. december 2021 har alle private virksomheder med 250+ ansatte, været forpligtet til at have et whistleblowerprogram. For virksomheder i den private sektor med mellem 50-249 ansatte, udløber fristen til at etablere whistleblowerordninger dog først 17. december 2023.</p>

      <h3 data-lang-en="Whistleblower scheme with Sixtus" data-lang-da="Whistleblowerordning med Sixtus">Whistleblowerordning med Sixtus</h3>
      <p data-lang-en="The key requirement is protecting whistleblowers from consequences linked to good-faith reports. Emails with internal users are not enough; companies must ensure the whistleblower’s identity is 100% confidential." data-lang-da="Fælles er for alle er, at det skal kunne sikres, at whistlebloweren bliver beskyttet mod de potentielle konsekvenser, som er forbundet med en indberetning afgivet i god tro. Dermed er e-mails med interne brugere heller ikke nok; virksomheden skal sikre, at whistleblowerens identitet kan holdes 100% fortrolig.">Fælles er for alle er, at det skal kunne sikres, at whistlebloweren bliver beskyttet mod de potentielle konsekvenser, som er forbundet med en indberetning afgivet i god tro. Dermed er e-mails med interne brugere heller ikke nok; virksomheden skal sikre, at whistleblowerens identitet kan holdes 100% fortrolig.</p>
      <p data-lang-en="With Sixtus by your side, you get help with implementation and support throughout the process. The implementation package includes the following services:" data-lang-da="Med Sixtus på sidelinjen, får du hjælp til implementering og support i hele processen. Implementeringspakken inkluderer følgende services:">Med Sixtus på sidelinjen, får du hjælp til implementering og support i hele processen. Implementeringspakken inkluderer følgende services:</p>
      <ul class="icon-list icon-list--columns">
        <li data-lang-en="Internal training" data-lang-da="Intern undervisning"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Intern undervisning</li>
        <li data-lang-en="Implementation of whistleblower policy" data-lang-da="Implementering af whistleblowerpolitik"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Implementering af whistleblowerpolitik</li>
        <li data-lang-en="Implementation of internal processes" data-lang-da="Implementering af interne processer"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Implementering af interne processer</li>
        <li data-lang-en="Processes for handling reports" data-lang-da="Processer for håndteringen af anmeldelser"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Processer for håndteringen af anmeldelser</li>
        <li data-lang-en="Help setting up an internal/external whistleblower board" data-lang-da="Hjælp til oprettelse af et internt/eksternt whistleblowerboard"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Hjælp til oprettelse af et internt/eksternt whistleblowerboard</li>
        <li data-lang-en="Monitoring, validation, and handling of incoming cases" data-lang-da="Overvågning, validering og håndtering af indkomne sager"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Overvågning, validering og håndtering af indkomne sager</li>
        <li data-lang-en="Access to legal assistance in complex cases" data-lang-da="Adgang til juridisk bistand ved komplicerede sager"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Adgang til juridisk bistand ved komplicerede sager</li>
        <li data-lang-en="Reporting and report writing" data-lang-da="Rapportering og rapportskrivning"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/icon-check.svg'); ?>" alt="" width="20" height="20" loading="lazy"> Rapportering og rapportskrivning</li>
      </ul>
    </div>
  </div>
</section>
<?php endif; ?>
