<?php
/*
Template Name: Privacy Policy
*/
get_header();
?>

<!-- Privacy policy breadcrumb -->
<?php get_template_part('template-parts/breadcrumbs'); ?>

<!-- Legal content -->
<section class="section">
  <div class="container">
    <div class="section-header">
      <h1 data-lang-en="Privacy Policy" data-lang-da="Privacy Policy">Privacy Policy</h1>
      <p data-lang-en="We take the protection of data seriously." data-lang-da="We take the protection of data seriously.">We take the protection of data seriously.</p>
    </div>

    <div class="legal-content">
      <p data-lang-en="Sixtus Compliance and Sixtus Technologies takes the protection of data, including personal data, seriously. Sixtus is responsible for the specific and legitimate purposes with, and means to, processing data – including personal data – and is obliged to protect your information." data-lang-da="Sixtus Compliance and Sixtus Technologies takes the protection of data, including personal data, seriously. Sixtus is responsible for the specific and legitimate purposes with, and means to, processing data – including personal data – and is obliged to protect your information.">Sixtus Compliance and Sixtus Technologies takes the protection of data, including personal data, seriously. Sixtus is responsible for the specific and legitimate purposes with, and means to, processing data – including personal data – and is obliged to protect your information.</p>
      <p data-lang-en="We process personal data and have, thus, composed this privacy policy, which explains how we process your personal data. Furthermore, Sixtus is obliged to secure, that the processing of your personal data takes place in accordance with the European Parliament and Council’s regulation (EU) 2016/679 of April 27th 2016, regarding protection of physical individuals in relation to the processing of personal data." data-lang-da="We process personal data and have, thus, composed this privacy policy, which explains how we process your personal data. Furthermore, Sixtus is obliged to secure, that the processing of your personal data takes place in accordance with the European Parliament and Council’s regulation (EU) 2016/679 of April 27th 2016, regarding protection of physical individuals in relation to the processing of personal data.">We process personal data and have, thus, composed this privacy policy, which explains how we process your personal data. Furthermore, Sixtus is obliged to secure, that the processing of your personal data takes place in accordance with the European Parliament and Council’s regulation (EU) 2016/679 of April 27th 2016, regarding protection of physical individuals in relation to the processing of personal data.</p>
      <p data-lang-en="When you visit our website, you accept the contents of this privacy policy and any other documents mentioned within the policy. This privacy policy defines how we treat all personally identifiable data that are collected. If you do not agree to the terms, we ask you to not make use of this website." data-lang-da="When you visit our website, you accept the contents of this privacy policy and any other documents mentioned within the policy. This privacy policy defines how we treat all personally identifiable data that are collected. If you do not agree to the terms, we ask you to not make use of this website.">When you visit our website, you accept the contents of this privacy policy and any other documents mentioned within the policy. This privacy policy defines how we treat all personally identifiable data that are collected. If you do not agree to the terms, we ask you to not make use of this website.</p>
      <p data-lang-en="Moreover, the privacy policy describes the security measures we relate to in order to protect your personal data, your right to access, correct or erase personal data and the right to make a complaint to the data protection agency. Also, we continuously assess how high the risk is that our data processing will effect your basic rights negatively." data-lang-da="Moreover, the privacy policy describes the security measures we relate to in order to protect your personal data, your right to access, correct or erase personal data and the right to make a complaint to the data protection agency. Also, we continuously assess how high the risk is that our data processing will effect your basic rights negatively.">Moreover, the privacy policy describes the security measures we relate to in order to protect your personal data, your right to access, correct or erase personal data and the right to make a complaint to the data protection agency. Also, we continuously assess how high the risk is that our data processing will effect your basic rights negatively.</p>

      <h2 data-lang-en="Use of the website" data-lang-da="Use of the website">Use of the website</h2>
      <h3 data-lang-en="Proprietary rights" data-lang-da="Proprietary rights">Proprietary rights</h3>
      <p data-lang-en="This website is owned and run by Sixtus Compliance and Sixtus Technologies (in the below named “Sixtus”)." data-lang-da="This website is owned and run by Sixtus Compliance and Sixtus Technologies (in the below named “Sixtus”).">This website is owned and run by Sixtus Compliance and Sixtus Technologies (in the below named “Sixtus”).</p>
      <h3 data-lang-en="User license" data-lang-da="User license">User license</h3>
      <p data-lang-en="When you are on the website, you are welcome to take a look around. Sixtus gives you permission to view this website, print and download the material shown on this site for your own personal use, given that you – without conditions – accept the terms and conditions within our policies, and given that you make sure that all injunctions and prohibitions concerning copyright, trademark and other proprietary rights are respected. However, you cannot in any way without written consent from Sixtus, copy, reproduce, upload, forward or distribute the contents of this website, including texts, images, audio and videos, for public or commercial purposes. The contents of this website may not be placed in the frames of third party websites either (prohibition against framing)." data-lang-da="When you are on the website, you are welcome to take a look around. Sixtus gives you permission to view this website, print and download the material shown on this site for your own personal use, given that you – without conditions – accept the terms and conditions within our policies, and given that you make sure that all injunctions and prohibitions concerning copyright, trademark and other proprietary rights are respected. However, you cannot in any way without written consent from Sixtus, copy, reproduce, upload, forward or distribute the contents of this website, including texts, images, audio and videos, for public or commercial purposes. The contents of this website may not be placed in the frames of third party websites either (prohibition against framing).">When you are on the website, you are welcome to take a look around. Sixtus gives you permission to view this website, print and download the material shown on this site for your own personal use, given that you – without conditions – accept the terms and conditions within our policies, and given that you make sure that all injunctions and prohibitions concerning copyright, trademark and other proprietary rights are respected. However, you cannot in any way without written consent from Sixtus, copy, reproduce, upload, forward or distribute the contents of this website, including texts, images, audio and videos, for public or commercial purposes. The contents of this website may not be placed in the frames of third party websites either (prohibition against framing).</p>
      <h3 data-lang-en="Intellectual property rights" data-lang-da="Intellectual property rights">Intellectual property rights</h3>
      <p data-lang-en="Texts, layout, illustrations, databases and other parts of this website, including the website itself, are protected by copyright and by the rights of the producer of this database. Certain names, brands and logos on this website are protected trademarks." data-lang-da="Texts, layout, illustrations, databases and other parts of this website, including the website itself, are protected by copyright and by the rights of the producer of this database. Certain names, brands and logos on this website are protected trademarks.">Texts, layout, illustrations, databases and other parts of this website, including the website itself, are protected by copyright and by the rights of the producer of this database. Certain names, brands and logos on this website are protected trademarks.</p>
      <p data-lang-en="Nothing on this website can be interpreted as a licensing right or any other right to use any trademark that is shown on this website, without written consent from Sixtus or third party who may own the trademarks shown on this website." data-lang-da="Nothing on this website can be interpreted as a licensing right or any other right to use any trademark that is shown on this website, without written consent from Sixtus or third party who may own the trademarks shown on this website.">Nothing on this website can be interpreted as a licensing right or any other right to use any trademark that is shown on this website, without written consent from Sixtus or third party who may own the trademarks shown on this website.</p>
      <p data-lang-en="Any form of copying, processing, translation, modification and any use of all or parts of this website or its protected elements in any form and in any way, is prohibited." data-lang-da="Any form of copying, processing, translation, modification and any use of all or parts of this website or its protected elements in any form and in any way, is prohibited.">Any form of copying, processing, translation, modification and any use of all or parts of this website or its protected elements in any form and in any way, is prohibited.</p>

      <h2 data-lang-en="Contact information" data-lang-da="Contact information">Contact information</h2>
      <ul>
        <li data-lang-en="Contact person: Bjørn Leth Erichsen" data-lang-da="Contact person: Bjørn Leth Erichsen">Contact person: Bjørn Leth Erichsen</li>
        <li data-lang-en="Address: Orient Plads 1, mezz." data-lang-da="Address: Orient Plads 1, mezz.">Address: Orient Plads 1, mezz.</li>
        <li data-lang-en="DK-2150 Nordhavn, Denmark" data-lang-da="DK-2150 Nordhavn, Denmark">DK-2150 Nordhavn, Denmark</li>
  <li data-lang-en="Central Business Register number.: 40649832 - 41483261" data-lang-da="Central Business Register number.: 40649832 - 41483261">Central Business Register number.: 40649832 - 41483261</li>
        <li data-lang-en="Telephone: +4551781999" data-lang-da="Telephone: +4551781999">Telephone: +4551781999</li>
        <li data-lang-en="E-mail: bjorn@sixtus-compliance.dk" data-lang-da="E-mail: bjorn@sixtus-compliance.dk">E-mail: bjorn@sixtus-compliance.dk</li>
        <li data-lang-en="Website: www.sixtus-compliance.dk" data-lang-da="Website: www.sixtus-compliance.dk">Website: www.sixtus-compliance.dk</li>
      </ul>
      <p data-lang-en="Sixtus is data controller, and we assure that your personal data are processed in accordance with the law." data-lang-da="Sixtus is data controller, and we assure that your personal data are processed in accordance with the law.">Sixtus is data controller, and we assure that your personal data are processed in accordance with the law.</p>

      <h2 data-lang-en="Processing of personal data" data-lang-da="Processing of personal data">Processing of personal data</h2>
      <h3 data-lang-en="We process these types of data about you" data-lang-da="We process these types of data about you">We process these types of data about you</h3>
      <p data-lang-en="Personal data covers all types of information which can be used to identify a person, including, but not limited to, first and last name, age, gender, private address or other physical address, mobile phone number, e-mail address or other contact information, regardless of whether they relate to the person’s private residence or work place." data-lang-da="Personal data covers all types of information which can be used to identify a person, including, but not limited to, first and last name, age, gender, private address or other physical address, mobile phone number, e-mail address or other contact information, regardless of whether they relate to the person’s private residence or work place.">Personal data covers all types of information which can be used to identify a person, including, but not limited to, first and last name, age, gender, private address or other physical address, mobile phone number, e-mail address or other contact information, regardless of whether they relate to the person’s private residence or work place.</p>
      <p data-lang-en="We process data about you to make our service better and secure quality in our products and services and in our contact with you." data-lang-da="We process data about you to make our service better and secure quality in our products and services and in our contact with you.">We process data about you to make our service better and secure quality in our products and services and in our contact with you.</p>

      <h3 data-lang-en="Automatic collection of data" data-lang-da="Automatic collection of data">Automatic collection of data</h3>
      <p data-lang-en="Our digital solutions are based on different technologies with the purpose of securing user-friendliness and security. These technologies can automatically collect data in order to offer the best possible solution, either directly or through third party on behalf of us. Cookies and analysis of clickstream data are examples of this, cf. below." data-lang-da="Our digital solutions are based on different technologies with the purpose of securing user-friendliness and security. These technologies can automatically collect data in order to offer the best possible solution, either directly or through third party on behalf of us. Cookies and analysis of clickstream data are examples of this, cf. below.">Our digital solutions are based on different technologies with the purpose of securing user-friendliness and security. These technologies can automatically collect data in order to offer the best possible solution, either directly or through third party on behalf of us. Cookies and analysis of clickstream data are examples of this, cf. below.</p>

      <h3 data-lang-en="Use of cookies" data-lang-da="Use of cookies">Use of cookies</h3>
      <h4 data-lang-en="Cookies, purpose and relevance" data-lang-da="Cookies, purpose and relevance">Cookies, purpose and relevance</h4>
      <p data-lang-en="If we place cookies, you will be informed of the usage and purpose with gathering the data via cookies." data-lang-da="If we place cookies, you will be informed of the usage and purpose with gathering the data via cookies.">If we place cookies, you will be informed of the usage and purpose with gathering the data via cookies.</p>
      <h4 data-lang-en="We collect your consent" data-lang-da="We collect your consent">We collect your consent</h4>
      <p data-lang-en="Before placing cookies on your equipment, we ask for your consent. Necessary cookies to secure functionalities and settings, can, however, be applied without your consent. We do currently not use any cookies that track, or in any way collect or store your data." data-lang-da="Before placing cookies on your equipment, we ask for your consent. Necessary cookies to secure functionalities and settings, can, however, be applied without your consent. We do currently not use any cookies that track, or in any way collect or store your data.">Before placing cookies on your equipment, we ask for your consent. Necessary cookies to secure functionalities and settings, can, however, be applied without your consent. We do currently not use any cookies that track, or in any way collect or store your data.</p>

      <h3 data-lang-en="Information that you actively submit" data-lang-da="Information that you actively submit">Information that you actively submit</h3>
      <p data-lang-en="In addition to the information that is automatically collected, we also process data that the users have actively given to us. Examples of data that the users actively submit:" data-lang-da="In addition to the information that is automatically collected, we also process data that the users have actively given to us. Examples of data that the users actively submit:">In addition to the information that is automatically collected, we also process data that the users have actively given to us. Examples of data that the users actively submit:</p>
      <ul>
        <li data-lang-en="E-mail, phone number, address, date of birth, payment information etc." data-lang-da="E-mail, phone number, address, date of birth, payment information etc.">E-mail, phone number, address, date of birth, payment information etc.</li>
      </ul>

      <h3 data-lang-en="We collect and store your personal information for specific purposes" data-lang-da="We collect and store your personal information for specific purposes">We collect and store your personal information for specific purposes</h3>
      <p data-lang-en="We collect and store your personal information related to specific purposes or other legal business-related purposes. This happens when we need to: (non-exhaustive list!)" data-lang-da="We collect and store your personal information related to specific purposes or other legal business-related purposes. This happens when we need to: (non-exhaustive list!)">We collect and store your personal information related to specific purposes or other legal business-related purposes. This happens when we need to: (non-exhaustive list!)</p>
      <ul>
        <li data-lang-en="Have an archive of the registered products and associated personal information" data-lang-da="Have an archive of the registered products and associated personal information">Have an archive of the registered products and associated personal information</li>
        <li data-lang-en="Confirm your identity during communication with us" data-lang-da="Confirm your identity during communication with us">Confirm your identity during communication with us</li>
        <li data-lang-en="With your specific consent, be able to contact you via the contact information that you have submitted, for marketing, sales, commercial and analyses purposes." data-lang-da="With your specific consent, be able to contact you via the contact information that you have submitted, for marketing, sales, commercial and analyses purposes.">With your specific consent, be able to contact you via the contact information that you have submitted, for marketing, sales, commercial and analyses purposes.</li>
      </ul>

      <h3 data-lang-en="We only process relevant personal data" data-lang-da="We only process relevant personal data">We only process relevant personal data</h3>
      <p data-lang-en="We only process data about you that are relevant and sufficient in relation to the specific purposes. The purpose is decisive to which type of data associated with you is relevant to us. The same applies to the extent of the personal information we use. I.e. we do not use more data than what we need for the specific purpose." data-lang-da="We only process data about you that are relevant and sufficient in relation to the specific purposes. The purpose is decisive to which type of data associated with you is relevant to us. The same applies to the extent of the personal information we use. I.e. we do not use more data than what we need for the specific purpose.">We only process data about you that are relevant and sufficient in relation to the specific purposes. The purpose is decisive to which type of data associated with you is relevant to us. The same applies to the extent of the personal information we use. I.e. we do not use more data than what we need for the specific purpose.</p>
      <p data-lang-en="Prior to processing your personal information, we investigate whether it is possible for us to minimise the amount of data about you. We also investigate if any of the data types we use can be used in an anonymised or pseudonymised form. We can do this if it does not affect negatively on our obligations or the services, we offer you." data-lang-da="Prior to processing your personal information, we investigate whether it is possible for us to minimise the amount of data about you. We also investigate if any of the data types we use can be used in an anonymised or pseudonymised form. We can do this if it does not affect negatively on our obligations or the services, we offer you.">Prior to processing your personal information, we investigate whether it is possible for us to minimise the amount of data about you. We also investigate if any of the data types we use can be used in an anonymised or pseudonymised form. We can do this if it does not affect negatively on our obligations or the services, we offer you.</p>

      <h3 data-lang-en="We only process necessary personal information" data-lang-da="We only process necessary personal information">We only process necessary personal information</h3>
      <p data-lang-en="We only collect, process and store the personal information necessary to fulfil our determined goals. Moreover, it can be provided by law which types of data are necessary to collect and store for our business operations. The type and extent of the personal information we process, can also be necessary to fulfil a contract or other legal obligations." data-lang-da="We only collect, process and store the personal information necessary to fulfil our determined goals. Moreover, it can be provided by law which types of data are necessary to collect and store for our business operations. The type and extent of the personal information we process, can also be necessary to fulfil a contract or other legal obligations.">We only collect, process and store the personal information necessary to fulfil our determined goals. Moreover, it can be provided by law which types of data are necessary to collect and store for our business operations. The type and extent of the personal information we process, can also be necessary to fulfil a contract or other legal obligations.</p>

      <h3 data-lang-en="We do not pass on your personal information without your consent" data-lang-da="We do not pass on your personal information without your consent">We do not pass on your personal information without your consent</h3>
      <p data-lang-en="If we pass your personal information on to business partners and operators, i.e. for marketing purposes, we collect your consent and inform about what the data will be used for. At any time, you can make objections against this type of transmission, and you can decline to receive enquiries for marketing purposes in the Civil Registration System." data-lang-da="If we pass your personal information on to business partners and operators, i.e. for marketing purposes, we collect your consent and inform about what the data will be used for. At any time, you can make objections against this type of transmission, and you can decline to receive enquiries for marketing purposes in the Civil Registration System.">If we pass your personal information on to business partners and operators, i.e. for marketing purposes, we collect your consent and inform about what the data will be used for. At any time, you can make objections against this type of transmission, and you can decline to receive enquiries for marketing purposes in the Civil Registration System.</p>
      <p data-lang-en="We do not collect your consent if we are legally obliged to pass on your personal information, i.e. as part of our reporting to the authorities." data-lang-da="We do not collect your consent if we are legally obliged to pass on your personal information, i.e. as part of our reporting to the authorities.">We do not collect your consent if we are legally obliged to pass on your personal information, i.e. as part of our reporting to the authorities.</p>

      <h3 data-lang-en="We protect your personal information and have internal rules concerning IT-security" data-lang-da="We protect your personal information and have internal rules concerning IT-security">We protect your personal information and have internal rules concerning IT-security</h3>
      <p data-lang-en="We have established internal rules on information security, which entail instructions and precautions that protect your personal information from being erased, lost or altered, against unauthorised release and against unauthorized access or knowledge of them." data-lang-da="We have established internal rules on information security, which entail instructions and precautions that protect your personal information from being erased, lost or altered, against unauthorised release and against unauthorized access or knowledge of them.">We have established internal rules on information security, which entail instructions and precautions that protect your personal information from being erased, lost or altered, against unauthorised release and against unauthorized access or knowledge of them.</p>
      <p data-lang-en="We have established procedures for assigning access rights to those of our employees that process sensitive personal data and data that reveal information on personal interests and habits. We control their actual access through logging and supervision. To avoid data loss, we continuously take data backups. We also protect the confidentiality and the authenticity of your data through encryption." data-lang-da="We have established procedures for assigning access rights to those of our employees that process sensitive personal data and data that reveal information on personal interests and habits. We control their actual access through logging and supervision. To avoid data loss, we continuously take data backups. We also protect the confidentiality and the authenticity of your data through encryption.">We have established procedures for assigning access rights to those of our employees that process sensitive personal data and data that reveal information on personal interests and habits. We control their actual access through logging and supervision. To avoid data loss, we continuously take data backups. We also protect the confidentiality and the authenticity of your data through encryption.</p>
      <p data-lang-en="In case of a security breach, which results in a high risk of discrimination, ID theft, financial loss, loss of reputation or other significant disadvantage, we are obliged to inform you of the security breach as soon as possible." data-lang-da="In case of a security breach, which results in a high risk of discrimination, ID theft, financial loss, loss of reputation or other significant disadvantage, we are obliged to inform you of the security breach as soon as possible.">In case of a security breach, which results in a high risk of discrimination, ID theft, financial loss, loss of reputation or other significant disadvantage, we are obliged to inform you of the security breach as soon as possible.</p>

      <h2 data-lang-en="Your rights" data-lang-da="Your rights">Your rights</h2>
      <h3 data-lang-en="You have the right to access your personal information" data-lang-da="You have the right to access your personal information">You have the right to access your personal information</h3>
      <p data-lang-en="At any time, you have the right to know which data we process about you, where they come from, and what we use them for. You can also be informed about for how long we store your personal data, and who receives data about you, to the extent that we pass on information in Denmark and abroad." data-lang-da="At any time, you have the right to know which data we process about you, where they come from, and what we use them for. You can also be informed about for how long we store your personal data, and who receives data about you, to the extent that we pass on information in Denmark and abroad.">At any time, you have the right to know which data we process about you, where they come from, and what we use them for. You can also be informed about for how long we store your personal data, and who receives data about you, to the extent that we pass on information in Denmark and abroad.</p>
      <p data-lang-en="Per your request, we can inform you about the data we process about you. This access may, however, be limited by the consideration of other persons’ privacy rights, trade secrets and intellectual property rights." data-lang-da="Per your request, we can inform you about the data we process about you. This access may, however, be limited by the consideration of other persons’ privacy rights, trade secrets and intellectual property rights.">Per your request, we can inform you about the data we process about you. This access may, however, be limited by the consideration of other persons’ privacy rights, trade secrets and intellectual property rights.</p>
      <p data-lang-en="You can make use of your rights by contacting us. Our contact information can be found in the beginning of this policy. We strive to accommodate your request as soon as possible and no later than a month after we receive your enquiry." data-lang-da="You can make use of your rights by contacting us. Our contact information can be found in the beginning of this policy. We strive to accommodate your request as soon as possible and no later than a month after we receive your enquiry.">You can make use of your rights by contacting us. Our contact information can be found in the beginning of this policy. We strive to accommodate your request as soon as possible and no later than a month after we receive your enquiry.</p>

      <h3 data-lang-en="You have the right to have inaccurate personal information corrected or deleted" data-lang-da="You have the right to have inaccurate personal information corrected or deleted">You have the right to have inaccurate personal information corrected or deleted</h3>
      <p data-lang-en="If you find the personal information, we process about you to be inaccurate, you have the right to have it corrected. You should contact us and inform us of the inaccuracies and how to correct them." data-lang-da="If you find the personal information, we process about you to be inaccurate, you have the right to have it corrected. You should contact us and inform us of the inaccuracies and how to correct them.">If you find the personal information, we process about you to be inaccurate, you have the right to have it corrected. You should contact us and inform us of the inaccuracies and how to correct them.</p>
      <p data-lang-en="When you contact us with a request to correct or delete your personal information, we will investigate whether the conditions are met, and then, we will correct or delete the information as soon as possible and no later than a month after we have received your enquiry." data-lang-da="When you contact us with a request to correct or delete your personal information, we will investigate whether the conditions are met, and then, we will correct or delete the information as soon as possible and no later than a month after we have received your enquiry.">When you contact us with a request to correct or delete your personal information, we will investigate whether the conditions are met, and then, we will correct or delete the information as soon as possible and no later than a month after we have received your enquiry.</p>

      <h3 data-lang-en="You have the right to object to our processing of your personal information" data-lang-da="You have the right to object to our processing of your personal information">You have the right to object to our processing of your personal information</h3>
      <p data-lang-en="You have the right to object to our processing of your personal information. You can also object to our transmission of your data for marketing purposes. Make use of the contact information at the top to send us your objection. If your objection is legitimate, we will make sure to discontinue the processing of your personal information." data-lang-da="You have the right to object to our processing of your personal information. You can also object to our transmission of your data for marketing purposes. Make use of the contact information at the top to send us your objection. If your objection is legitimate, we will make sure to discontinue the processing of your personal information.">You have the right to object to our processing of your personal information. You can also object to our transmission of your data for marketing purposes. Make use of the contact information at the top to send us your objection. If your objection is legitimate, we will make sure to discontinue the processing of your personal information.</p>
      <p data-lang-en="If you wish to object to our data processing, we will check to see if it is possible and answer your enquiry as soon as possible and no later than a month after receiving it." data-lang-da="If you wish to object to our data processing, we will check to see if it is possible and answer your enquiry as soon as possible and no later than a month after receiving it.">If you wish to object to our data processing, we will check to see if it is possible and answer your enquiry as soon as possible and no later than a month after receiving it.</p>

      <h3 data-lang-en="Access to information" data-lang-da="Access to information">Access to information</h3>
      <p data-lang-en="Questions and comments to this privacy policy can be directed at bjorn@sixtus-compliance.dk. If you want to know which information we have registered about you, receive a copy of the information or have us delete or correct your information, you can write to us at bjorn@sixtus-compliance.dk." data-lang-da="Questions and comments to this privacy policy can be directed at bjorn@sixtus-compliance.dk. If you want to know which information we have registered about you, receive a copy of the information or have us delete or correct your information, you can write to us at bjorn@sixtus-compliance.dk.">Questions and comments to this privacy policy can be directed at bjorn@sixtus-compliance.dk. If you want to know which information we have registered about you, receive a copy of the information or have us delete or correct your information, you can write to us at bjorn@sixtus-compliance.dk.</p>
      <p data-lang-en="If you are not content with our response, you can file a complaint with the Danish Data Protection Agency (Datatilsynet)" data-lang-da="If you are not content with our response, you can file a complaint with the Danish Data Protection Agency (Datatilsynet)">If you are not content with our response, you can file a complaint with the Danish Data Protection Agency (Datatilsynet)</p>

      <h2 data-lang-en="Datatilsynet" data-lang-da="Datatilsynet">Datatilsynet</h2>
      <ul>
        <li data-lang-en="Carl Jacobsens Vej 35" data-lang-da="Carl Jacobsens Vej 35">Carl Jacobsens Vej 35</li>
        <li data-lang-en="DK-2500 Valby" data-lang-da="DK-2500 Valby">DK-2500 Valby</li>
        <li data-lang-en="Telephone: +45 33 19 32 00" data-lang-da="Telephone: +45 33 19 32 00">Telephone: +45 33 19 32 00</li>
        <li data-lang-en="E-mail: dt@datatilsynet.dk" data-lang-da="E-mail: dt@datatilsynet.dk">E-mail: dt@datatilsynet.dk</li>
      </ul>
    </div>
  </div>
</section>

<section class="section">
  <div class="container legal-grid">
    <div class="card">
      <h3 data-lang-en="Kontakt" data-lang-da="Kontakt">Kontakt</h3>
      <p>Sixtus Compliance &amp; Sixtus Technologies</p>
      <p>Store Regnegade 2<br>DK-1110 København K</p>
      <p>Copenhagen Legal Tech Hub</p>
      <p>CVR: 40649832 - 41483261</p>
      <p>Phone: +45 30 65 43 35</p>
      <p>Email: info@sixtus-compliance.dk</p>
    </div>
    <div class="card">
      <h3 data-lang-en="Mere om Sixtus" data-lang-da="Mere om Sixtus">Mere om Sixtus</h3>
      <ul>
        <li>Om Sixtus</li>
        <li>Privacy policy</li>
        <li>RSS Datatilsynet</li>
        <li>Datatilsynet afholdt webinar for foreninger</li>
        <li>Datatilsynet giver 51 kommuner alvorlig…</li>
        <li>RSS European Data Protection Board</li>
        <li>Register now for our conference…</li>
        <li>Stakeholder event on political advertising:…</li>
        <li>Data Protection Day 2026: keeping…</li>
      </ul>
    </div>
    <div class="card">
      <h3 data-lang-en="Certifications" data-lang-da="Certifications">Certifications</h3>
      <ul>
        <li>CIPM logo</li>
        <li>CIPP logo</li>
      </ul>
      <p>© Copyright 2026 | All Rights Reserved | Sixtus Compliance &amp; Sixtus Technologies</p>
  <p><a href="https://www.linkedin.com/company/sixtus-group/posts/?feedView=all" target="_blank" rel="noopener">LinkedIn</a></p>
      <p><a href="#content">Go to Top</a></p>
    </div>
  </div>
</section>

<?php get_footer(); ?>
